/*global systemDictionary:true */
'use strict';

systemDictionary = {
	'sqlstatistics adapter settings': {
		'en': 'Adapter settings for sqlstatistics',
		'de': 'Adaptereinstellungen für sqlstatistics',
		'ru': 'Настройки адаптера для sqlstatistics',
		'pt': 'Configurações do adaptador para sqlstatistics',
		'nl': 'Adapterinstellingen voor sqlstatistics',
		'fr': "Paramètres d'adaptateur pour sqlstatistics",
		'it': "Impostazioni dell'adattatore per sqlstatistics",
		'es': 'Ajustes del adaptador para sqlstatistics',
		'pl': 'Ustawienia adaptera dla sqlstatistics',
		'zh-cn': 'sqlstatistics的适配器设置'
	},
	'option1': {
		'en': 'option1',
		'de': 'Option 1',
		'ru': 'Опция 1',
		'pt': 'Opção 1',
		'nl': 'Optie 1',
		'fr': 'Option 1',
		'it': 'opzione 1',
		'es': 'Opción 1',
		'pl': 'opcja 1',
		'zh-cn': '选项1'
	},
	'option2': {
		'en': 'option2',
		'de': 'Option 2',
		'ru': 'option2',
		'pt': 'opção 2',
		'nl': 'Optie 2',
		'fr': 'Option 2',
		'it': 'opzione 2',
		'es': 'opcion 2',
		'pl': 'Opcja 2',
		'zh-cn': '选项2'
	},
	"Select sql history instance:": {
		"en": "Select sql history instance:",
		"de": "Wählen die SQL History Instanz aus:",
		"ru": "Выберите экземпляр истории sql:",
		"pt": "Selecione a instância do histórico sql:",
		"nl": "Selecteer sql history instance:",
		"fr": "Sélectionnez l'instance d'historique sql:",
		"it": "Seleziona l'istanza della cronologia sql:",
		"es": "Seleccione la instancia del historial de SQL:",
		"pl": "Wybierz wystąpienie historii sql:",
		"zh-cn": "选择SQL历史记录实例："
	},
	"Update interval for databases statistics in hours": {
		"en": "Update interval for databases statistics in hours",
		"de": "Aktualisierungsintervall für Datenbankstatistiken in Stunden",
		"ru": "Интервал обновления статистики баз данных в часах",
		"pt": "Intervalo de atualização para estatísticas de bancos de dados em horas",
		"nl": "Update-interval voor databasestatistieken in uren",
		"fr": "Intervalle de mise à jour des statistiques des bases de données en heures",
		"it": "Intervallo di aggiornamento per le statistiche dei database in ore",
		"es": "Intervalo de actualización para estadísticas de bases de datos en horas",
		"pl": "Aktualizacja interwału dla statystyk baz danych w godzinach",
		"zh-cn": "数据库统计信息的更新间隔（以小时为单位）"
	},
	"Update interval for system and client statistics in minutes": {
		"en": "Update interval for system and client statistics in minutes",
		"de": "Aktualisierungsintervall für System- und Clientstatistiken in Minuten",
		"ru": "Интервал обновления системной и клиентской статистики в минутах",
		"pt": "Intervalo de atualização para estatísticas do sistema e do cliente em minutos",
		"nl": "Update-interval voor systeem- en clientstatistieken in minuten",
		"fr": "Intervalle de mise à jour des statistiques système et client en minutes",
		"it": "Intervallo di aggiornamento per statistiche di sistema e client in minuti",
		"es": "Intervalo de actualización para estadísticas del sistema y del cliente en minutos",
		"pl": "Aktualizuj interwał dla statystyk systemu i klienta w kilka minut",
		"zh-cn": "系统和客户端统计信息的更新间隔（以分钟为单位）"
	},
	"Delete unused objects": {
		"en": "Delete unused objects",
		"de": "Nicht verwendete Objekte löschen",
		"ru": "Удалить неиспользуемые объекты",
		"pt": "Excluir objetos não utilizados",
		"nl": "Verwijder ongebruikte objecten",
		"fr": "Supprimer les objets inutilisés",
		"it": "Elimina oggetti inutilizzati",
		"es": "Eliminar objetos no utilizados",
		"pl": "Usuń nieużywane obiekty",
		"zh-cn": "删除未使用的对象"
	},
	"Database name": {
		"en": "Database name",
		"de": "Name der Datenbank",
		"ru": "Имя базы данных",
		"pt": "Nome do banco de dados",
		"nl": "Database naam",
		"fr": "Nom de la base de données",
		"it": "Nome del database",
		"es": "Nombre de la base de datos",
		"pl": "Nazwa bazy danych",
		"zh-cn": "数据库名称"
	},
	"Add database": {
		"en": "Add database",
		"de": "Datenbank hinzufügen",
		"ru": "Добавить базу данных",
		"pt": "Adicionar banco de dados",
		"nl": "Database toevoegen",
		"fr": "Ajouter une base de données",
		"it": "Aggiungi database",
		"es": "Agregar base de datos",
		"pl": "Dodaj bazę danych",
		"zh-cn": "添加数据库"
	},
	"Blacklist databases: databases that should not be in the statistic": {
		"en": "Blacklist databases: databases that should not be in the statistic",
		"de": "Blacklist-Datenbanken: Datenbanken, die nicht in der Statistik enthalten sein sollten",
		"ru": "Базы данных черного списка: базы данных, которых не должно быть в статистике",
		"pt": "Bancos de dados da lista negra: bancos de dados que não devem estar na estatística",
		"nl": "Blacklist databases: databases die niet in de statistiek mogen staan",
		"fr": "Bases de données de liste noire: bases de données qui ne devraient pas figurer dans la statistique",
		"it": "Database blacklist: database che non dovrebbero essere nella statistica",
		"es": "Bases de datos de listas negras: bases de datos que no deberían estar en la estadística",
		"pl": "Bazy danych z czarnej listy: bazy danych, które nie powinny znajdować się w statystykach",
		"zh-cn": "黑名单数据库：不应包含在统计信息中的数据库"
	},
	"create statistics for non ioBroker tables": {
		"en": "create statistics for non ioBroker tables",
		"de": "Statistiken für nicht ioBroker Tabellen erzeugen",
		"ru": "создать статистику для таблиц не ioBroker",
		"pt": "criar estatísticas para tabelas não ioBroker",
		"nl": "maak statistieken voor niet ioBroker-tabellen",
		"fr": "créer des statistiques pour les tables non ioBroker",
		"it": "creare statistiche per tabelle non ioBroker",
		"es": "crear estadísticas para tablas que no sean ioBroker",
		"pl": "tworzyć statystyki dla tabel innych niż ioBroker",
		"zh-cn": "为非ioBroker表创建统计信息"
	},
	"You like the adapter? Then support us with a small donation.": {
		"en": "You like the adapter? Then support the adapter developer (Scrounger) with a small donation.",
		"de": "Dir gefällt der Adapter? Dann unterstütze den Adapterentwickler (Scrounger) mit einer kleinen Spende.",
		"ru": "Вам нравится адаптер? Затем поддержите разработчика адаптера (Scrounger) с небольшим пожертвованием.",
		"pt": "Você gosta do adaptador? Depois, ofereça suporte ao desenvolvedor do adaptador (Scrounger) com uma pequena doação.",
		"nl": "Vind je de adapter leuk? Ondersteun vervolgens de adapterontwikkelaar (Scrounger) met een kleine donatie.",
		"fr": "Vous aimez l'adaptateur? Soutenez ensuite le développeur de l'adaptateur (Scrounger) avec un petit don.",
		"it": "Ti piace l'adattatore? Quindi supportare lo sviluppatore dell'adattatore (Scrounger) con una piccola donazione.",
		"es": "¿Te gusta el adaptador? Luego, apoye al desarrollador del adaptador (Scrounger) con una pequeña donación.",
		"pl": "Podoba ci się adapter? Następnie wesprzyj programistę adaptera (Scrounger) niewielką darowizną.",
		"zh-cn": "您喜欢适配器吗？然后以少量捐款支持适配器开发人员（Scrounger）。"
	},
	"setting for databases statistics": {
		"en": "setting for databases statistics",
		"de": "Einstellung für Datenbankstatistiken",
		"ru": "настройка для статистики баз данных",
		"pt": "configuração para estatísticas de bancos de dados",
		"nl": "instelling voor databasestatistieken",
		"fr": "paramétrage des statistiques des bases de données",
		"it": "impostazione per le statistiche dei database",
		"es": "configuración de estadísticas de bases de datos",
		"pl": "ustawienie dla statystyk baz danych",
		"zh-cn": "设置数据库统计信息"
	},
	"setting for system and client statistics": {
		"en": "setting for system and client statistics",
		"de": "Einstellung für System- und Client-Statistiken",
		"ru": "настройка для системной и клиентской статистики",
		"pt": "configuração para estatísticas do sistema e do cliente",
		"nl": "instelling voor systeem- en klantstatistieken",
		"fr": "réglage des statistiques système et client",
		"it": "impostazione per statistiche di sistema e client",
		"es": "configuración de estadísticas del sistema y del cliente",
		"pl": "ustawienie dla statystyk systemu i klienta",
		"zh-cn": "设置系统和客户端统计信息"
	},
	"enable system statistics": {
		"en": "enable system statistics",
		"de": "Systemstatistik aktivieren",
		"ru": "включить системную статистику",
		"pt": "ativar estatísticas do sistema",
		"nl": "systeemstatistieken inschakelen",
		"fr": "activer les statistiques du système",
		"it": "abilita le statistiche di sistema",
		"es": "habilitar estadísticas del sistema",
		"pl": "włącz statystyki systemowe",
		"zh-cn": "启用系统统计信息"
	},
	"enable client statistics": {
		"en": "enable client statistics",
		"de": "Client-Statistiken aktivieren",
		"ru": "включить статистику клиента",
		"pt": "ativar estatísticas do cliente",
		"nl": "klantstatistieken inschakelen",
		"fr": "activer les statistiques client",
		"it": "abilitare le statistiche del cliente",
		"es": "habilitar estadísticas del cliente",
		"pl": "włącz statystyki klienta",
		"zh-cn": "启用客户统计信息"
	}
};