/*global systemDictionary:true */
'use strict';

systemDictionary = {
	'sqlstatistics adapter settings': {
		'en': 'Adapter settings for sqlstatistics',
		'de': 'Adaptereinstellungen für sqlstatistics',
		'ru': 'Настройки адаптера для sqlstatistics',
		'pt': 'Configurações do adaptador para sqlstatistics',
		'nl': 'Adapterinstellingen voor sqlstatistics',
		'fr': "Paramètres d'adaptateur pour sqlstatistics",
		'it': "Impostazioni dell'adattatore per sqlstatistics",
		'es': 'Ajustes del adaptador para sqlstatistics',
		'pl': 'Ustawienia adaptera dla sqlstatistics',
		'zh-cn': 'sqlstatistics的适配器设置'
	},
	"SelectSqlHistoryInstance": {
		"en": "Select sql history instance:",
		"de": "Wählen die SQL History Instanz aus:",
		"ru": "Выберите экземпляр истории sql:",
		"pt": "Selecione a instância do histórico sql:",
		"nl": "Selecteer sql history instance:",
		"fr": "Sélectionnez l'instance d'historique sql:",
		"it": "Seleziona l'istanza della cronologia sql:",
		"es": "Seleccione la instancia del historial de SQL:",
		"pl": "Wybierz wystąpienie historii sql:",
		"zh-cn": "选择SQL历史记录实例："
	},
	"UpdateIntervalDatabases": {
		"en": "Update interval for databases statistics in hours",
		"de": "Aktualisierungsintervall für Datenbankstatistiken in Stunden",
		"ru": "Интервал обновления статистики баз данных в часах",
		"pt": "Intervalo de atualização para estatísticas de bancos de dados em horas",
		"nl": "Update-interval voor databasestatistieken in uren",
		"fr": "Intervalle de mise à jour des statistiques des bases de données en heures",
		"it": "Intervallo di aggiornamento per le statistiche dei database in ore",
		"es": "Intervalo de actualización para estadísticas de bases de datos en horas",
		"pl": "Aktualizacja interwału dla statystyk baz danych w godzinach",
		"zh-cn": "数据库统计信息的更新间隔（以小时为单位）"
	},
	"UpdateIntervalSystemOrSession": {
		"en": "Update interval for system and session statistics in minutes",
		"de": "Aktualisierungsintervall für System- und Sitzungsstatistiken in Minuten",
		"ru": "Интервал обновления системной и сессионной статистики в минутах",
		"pt": "Intervalo de atualização para estatísticas do sistema e da sessão em minutos",
		"nl": "Update-interval voor systeem- en sessiestatistieken in minuten",
		"fr": "Intervalle de mise à jour des statistiques système et de session en minutes",
		"it": "Intervallo di aggiornamento per le statistiche di sistema e di sessione in minuti",
		"es": "Intervalo de actualización para estadísticas del sistema y sesión en minutos",
		"pl": "Aktualizacja interwału dla statystyki systemu i sesji w minutach",
		"zh-cn": "系统和会话统计信息的更新间隔（以分钟为单位）"
	},
	"DatabaseName": {
		"en": "Database name",
		"de": "Name der Datenbank",
		"ru": "Имя базы данных",
		"pt": "Nome do banco de dados",
		"nl": "Database naam",
		"fr": "Nom de la base de données",
		"it": "Nome del database",
		"es": "Nombre de la base de datos",
		"pl": "Nazwa bazy danych",
		"zh-cn": "数据库名称"
	},
	"AddDatabase": {
		"en": "Add database",
		"de": "Datenbank hinzufügen",
		"ru": "Добавить базу данных",
		"pt": "Adicionar banco de dados",
		"nl": "Database toevoegen",
		"fr": "Ajouter une base de données",
		"it": "Aggiungi database",
		"es": "Agregar base de datos",
		"pl": "Dodaj bazę danych",
		"zh-cn": "添加数据库"
	},
	"BlacklistDatabases": {
		"en": "Blacklist databases: databases that should not be in the statistic",
		"de": "Blacklist-Datenbanken: Datenbanken, die nicht in der Statistik enthalten sein sollten",
		"ru": "Базы данных черного списка: базы данных, которых не должно быть в статистике",
		"pt": "Bancos de dados da lista negra: bancos de dados que não devem estar na estatística",
		"nl": "Blacklist databases: databases die niet in de statistiek mogen staan",
		"fr": "Bases de données de liste noire: bases de données qui ne devraient pas figurer dans la statistique",
		"it": "Database blacklist: database che non dovrebbero essere nella statistica",
		"es": "Bases de datos de listas negras: bases de datos que no deberían estar en la estadística",
		"pl": "Bazy danych z czarnej listy: bazy danych, które nie powinny znajdować się w statystykach",
		"zh-cn": "黑名单数据库：不应包含在统计信息中的数据库"
	},
	"createTableStatistics": {
		"en": "create statistics for non ioBroker tables",
		"de": "Statistiken für nicht ioBroker Tabellen erzeugen",
		"ru": "создать статистику для таблиц не ioBroker",
		"pt": "criar estatísticas para tabelas não ioBroker",
		"nl": "maak statistieken voor niet ioBroker-tabellen",
		"fr": "créer des statistiques pour les tables non ioBroker",
		"it": "creare statistiche per tabelle non ioBroker",
		"es": "crear estadísticas para tablas que no sean ioBroker",
		"pl": "tworzyć statystyki dla tabel innych niż ioBroker",
		"zh-cn": "为非ioBroker表创建统计信息"
	},
	"donationInfo": {
		"en": "You like the adapter? Then support the adapter developer (Scrounger) with a small donation.",
		"de": "Dir gefällt der Adapter? Dann unterstütze den Adapterentwickler (Scrounger) mit einer kleinen Spende.",
		"ru": "Вам нравится адаптер? Затем поддержите разработчика адаптера (Scrounger) с небольшим пожертвованием.",
		"pt": "Você gosta do adaptador? Depois, ofereça suporte ao desenvolvedor do adaptador (Scrounger) com uma pequena doação.",
		"nl": "Vind je de adapter leuk? Ondersteun vervolgens de adapterontwikkelaar (Scrounger) met een kleine donatie.",
		"fr": "Vous aimez l'adaptateur? Soutenez ensuite le développeur de l'adaptateur (Scrounger) avec un petit don.",
		"it": "Ti piace l'adattatore? Quindi supportare lo sviluppatore dell'adattatore (Scrounger) con una piccola donazione.",
		"es": "¿Te gusta el adaptador? Luego, apoye al desarrollador del adaptador (Scrounger) con una pequeña donación.",
		"pl": "Podoba ci się adapter? Następnie wesprzyj programistę adaptera (Scrounger) niewielką darowizną.",
		"zh-cn": "您喜欢适配器吗？然后以少量捐款支持适配器开发人员（Scrounger）。"
	},
	"settingDatabasesStatistics": {
		"en": "setting for databases statistics",
		"de": "Einstellung für Datenbankstatistiken",
		"ru": "настройка для статистики баз данных",
		"pt": "configuração para estatísticas de bancos de dados",
		"nl": "instelling voor databasestatistieken",
		"fr": "paramétrage des statistiques des bases de données",
		"it": "impostazione per le statistiche dei database",
		"es": "configuración de estadísticas de bases de datos",
		"pl": "ustawienie dla statystyk baz danych",
		"zh-cn": "设置数据库统计信息"
	},
	"settingSystemOrSessionStatistics": {
		"en": "setting for system and session statistics",
		"de": "Einstellung für System- und Sitzungsstatistik",
		"ru": "настройка для системной и сеансовой статистики",
		"pt": "configuração para estatísticas do sistema e da sessão",
		"nl": "instelling voor systeem- en sessiestatistieken",
		"fr": "réglage des statistiques système et de session",
		"it": "impostazione per statistiche di sistema e di sessione",
		"es": "Configuración de estadísticas de sistema y sesión",
		"pl": "ustawienie statystyk systemu i sesji",
		"zh-cn": "设置系统和会话统计信息"
	},
	"enableSystemStatistics": {
		"en": "enable system statistics",
		"de": "Systemstatistik aktivieren",
		"ru": "включить системную статистику",
		"pt": "ativar estatísticas do sistema",
		"nl": "systeemstatistieken inschakelen",
		"fr": "activer les statistiques du système",
		"it": "abilita le statistiche di sistema",
		"es": "habilitar estadísticas del sistema",
		"pl": "włącz statystyki systemowe",
		"zh-cn": "启用系统统计信息"
	},
	"enableSessionStatistics": {
		"en": "enable session statistics",
		"de": "Sitzungsstatistik aktivieren",
		"ru": "включить статистику сеанса",
		"pt": "ativar estatísticas da sessão",
		"nl": "sessiestatistieken inschakelen",
		"fr": "activer les statistiques de session",
		"it": "abilita le statistiche di sessione",
		"es": "habilitar estadísticas de sesión",
		"pl": "włącz statystyki sesji",
		"zh-cn": "启用会话统计"
	},
	"general": {
		"en": "general",
		"de": "Allgemein",
		"ru": "Общее",
		"pt": "geral",
		"nl": "algemeen",
		"fr": "général",
		"it": "generale",
		"es": "general",
		"pl": "generał",
		"zh-cn": "一般"
	},
	"systemDatapoints": {
		"en": "system datapoints",
		"de": "System Datenpunkte",
		"ru": "системные данные",
		"pt": "pontos de dados do sistema",
		"nl": "systeemgegevenspunten",
		"fr": "points de données système",
		"it": "punti dati di sistema",
		"es": "puntos de datos del sistema",
		"pl": "systemowe punkty danych",
		"zh-cn": "系统数据点"
	},
	"sessionDatapoints": {
		"en": "session datapoints",
		"de": "Sitzungs Datenpunkte",
		"ru": "точки данных сеанса",
		"pt": "pontos de dados da sessão",
		"nl": "sessie datapunten",
		"fr": "points de données de session",
		"it": "punti dati della sessione",
		"es": "puntos de datos de sesión",
		"pl": "punkty danych sesji",
		"zh-cn": "会话数据点"
	},
	"DatapointsSelectionNotYetAvailable": {
		"en": "Datapoints selection not yet available, adapter must successfully run 1 time to show available datapoints!",
		"de": "Datenpunktauswahl noch nicht verfügbar, Adapter muss 1 Mal erfolgreich ausgeführt werden, um verfügbare Datenpunkte anzuzeigen!",
		"ru": "Выбор точек данных еще не доступен, адаптер должен успешно запускаться 1 раз, чтобы показать доступные точки данных!",
		"pt": "Seleção de pontos de dados ainda não disponível, o adaptador deve ser executado com êxito 1 vez para mostrar os pontos de dados disponíveis!",
		"nl": "Datapunten selectie nog niet beschikbaar, adapter moet 1 keer succesvol draaien om de beschikbare datapunten te tonen!",
		"fr": "La sélection des points de données n'est pas encore disponible, l'adaptateur doit fonctionner avec succès 1 fois pour afficher les points de données disponibles!",
		"it": "Selezione dei punti dati non ancora disponibile, l'adattatore deve essere eseguito correttamente 1 volta per mostrare i punti dati disponibili!",
		"es": "¡La selección de puntos de datos aún no está disponible, el adaptador debe ejecutarse con éxito 1 vez para mostrar los puntos de datos disponibles!",
		"pl": "Wybór punktów danych nie jest jeszcze dostępny, adapter musi pomyślnie uruchomić 1 raz, aby wyświetlić dostępne punkty danych!",
		"zh-cn": "数据点选择尚不可用，适配器必须成功运行1次才能显示可用数据点！"
	}
};